# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96440b6082ce39465728ec2de2ce963c912534e6a687ee3dedeace304e334a0cd18a2f216a54ef6ed8ebf25c296ce3287f0e3f3abc1ed3d3ede82f85e27a5248

test:
  secret_key_base: e45dd9392d2b69383710d68dce5d652b6fa1812c07c7eef9bdfbaafe094afc2a141999297dc6e7e2ccce08089a2276ef481197bcafedcfb78a0fc6eeeeaa4f6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
